BASE_URL = 'https://testnet.binance.vision'
EXCHANGE_URL = '/api/v3/exchangeInfo'
LISTEN_URL = '/api/v3/userDataStream'
ORDER_URL = '/api/v3/order'
SERVER_TIME_URL = '/api/v3/time'
SYMBOL_PRICE_URL = '/api/v3/ticker/price'
WS_URL = 'wss://testnet.binance.vision/ws'
